# Podfile

# Select the appropriate platform below
platform :ios
# platform :osx

# Add Kiwi as an exclusive dependency for the AmazingAppTests target
target :iOSappTests, :exclusive => true do
   pod 'Kiwi'
   pod 'MagicalRecord'
   pod 'Facebook-iOS-SDK'
end

target :iOSapp, :exclusive => true do
   pod 'Facebook-iOS-SDK'
end
